### PR TITLE
Update to use Rails 5.1

### PR DESCRIPTION
**Pull request by julioalucero**
This is still in `wip`, the test are not green. 

1. I Replace `protected_attributes` by  protected_attributes_continued 
2. `ActionController::RedirectBackError` is deprecated, at the moment I rescue all doing `rescue Exception`
3. on `redirect_on_revert` method, we need to permit some params, not sure which ones so I keep: 
 `redirect_to url, {}.merge(redirect_params.permit)`
4. Rails 5.1 requires Ruby 2.2.2 or newer. So I updated the `travis.yml` file

### CODE REVIEW

**Comment by brnrdog** [comment]
You can replace the `redirect_to :back` and the `ActionController::RedirectBackError` with the `redirect_back` method with a fallback path.

```
redirect_back(fallback_location: root_path)
``

**Comment by mdpatrick** [comment]
Works. 👍👏

**Comment by josephpage** [comment]
Hey @rcook, it is possible to officially release v0.12.0 with Rails 5.1 support ?
Really appreciate.

**Comment by rcook** [comment]
@josephpage : I do not currently have time to maintain this project. I would be happy to add you as a project owner if that would help.

**Comment by julioalucero** [comment]
@rcook I don't have any problem on maintain it

**Comment by rcook** [comment]
@julioalucero : I've added you as a contributor. I'll also see if there's a way you can publish new versions to RubyGems.

**Comment by rcook** [comment]
@julioalucero : What's the e-mail address of your RubyGems account? I'll need that to allow you to push new versions out.

**Comment by julioalucero** [comment]
sure, poramo at gmail.com

**Comment by rcook** [comment]
@julioalucero : You're now an owner on RubyGems. Thanks!

**Pull request merged**
