### PR TITLE
Use current_staff instead of current_user for custom methods

### PR DESCRIPTION
**Pull request by vinayvinsol**
Use `current_staff` method by making it a helper and use it in views instead of `current_user` so that custom methods configuration can work everywhere and no extra `current_user` methods are to be made in `application_controller.rb`

### CODE REVIEW

**Comment by rcook** [comment]
I'm investigating how to fix the Travis-CI failure: I think this is unrelated to the proposed change.

However, I'm not sure what the purpose of this change is. Could you provide a little more background? I'll be happy to merge the change once I know what it's for!

**Comment by rcook** [comment]
I've fixed the Travis-CI build errors in https://github.com/rcook/user_impersonate2/commit/cad4333b38b2cc1c48a689cb7c18b6299086bbf1.

A thought: perhaps you could document this new API in `README.md`?

**Comment by vinayvinsol** [comment]
Hi @rcook, 
I am currently developing an spree application in which `current_user` method is `spree_current_user`. You have also specified the `spree` specific configurations in which one is  `config.current_staff = 'spree_current_user'`. But still there is a need to make a `current_user` helper in `application_ontroller.rb` which only returns `spree_current_user`. I found that in only views `current_user` method is used directly elsewhere you are fetching it from `current_staff` so using `current_staff` will no longer require `helper_method` in `application_controller.rb`

Let me know if you understand the requirement of change. :)

**Comment by vinayvinsol** [comment]
@rcook,
So you are saying i should update spree specific part of `README.md`. Also should i raise a PR for that also. ?

**Comment by rcook** [comment]
That would be great!

**Pull request merged**
